formatting + linting catches

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -23,45 +23,45 @@ DOT_DIR="$HOME/dotfiles"
 
 function cmd_help() {
   case "$1" in
-    dot)
-      echo -e "Description"
-      echo -e "\t Dotfiles manager"
-      echo -e "\nUsage"
-      echo -e "\t$(basename "$2") [options] <subcommand>"
-      echo -e "\nOptions"
-      echo -e "\t-h, --help\t this helpfule message"
-      echo -e "\nSubcommands"
-      echo -e "\tstow\t\t manages symlinks"
-      echo -e "\tdump\t\t dumps static configs"
-      ;;
-    stow)
-      echo -e "Description"
-      echo -e "\t Symlink manager (wraps Gnu Stow)"
-      echo -e "\nUsage"
-      echo -e "\t$(basename "$2") stow [options] <package> [<package> ...]"
-      echo -e "\nOptions"
-      echo -e "\t-h, --help\t\t this helpful message"
-      echo -e "\t-a, --all\t\t stow all packages"
-      echo -e "\t-t, --test\t\t testing mode, no change to file system"
-      echo -e "\t-e, --exclude\t exclude packages passed"
-      echo -e "\t-d, --delete\t delete existing links"
-      echo -e "\nArguments"
-      echo -e "\t<package>\t\t package basename to stow"
-      ;;
-    dump)
-      echo -e "Description"
-      echo -e "\t Dumps unlinked configs:"
-      echo -e "\t\t-Brewfile  (list of brew packages)"
-      echo -e "\t\t-Crontab   (cronjob settings)"
-      echo -e "\nUsage"
-      echo -e "\t$(basename "$2") dump [options]"
-      echo -e "\nOptions"
-      echo -e "\t-h, --help\t this helpful message"
-      ;;
-    *)
-      echo "Unknown help message '$1'"
-      exit 1
-      ;;
+  dot)
+    echo -e "Description"
+    echo -e "\t Dotfiles manager"
+    echo -e "\nUsage"
+    echo -e "\t$(basename "$2") [options] <subcommand>"
+    echo -e "\nOptions"
+    echo -e "\t-h, --help\t this helpfule message"
+    echo -e "\nSubcommands"
+    echo -e "\tstow\t\t manages symlinks"
+    echo -e "\tdump\t\t dumps static configs"
+    ;;
+  stow)
+    echo -e "Description"
+    echo -e "\t Symlink manager (wraps Gnu Stow)"
+    echo -e "\nUsage"
+    echo -e "\t$(basename "$2") stow [options] <package> [<package> ...]"
+    echo -e "\nOptions"
+    echo -e "\t-h, --help\t\t this helpful message"
+    echo -e "\t-a, --all\t\t stow all packages"
+    echo -e "\t-t, --test\t\t testing mode, no change to file system"
+    echo -e "\t-e, --exclude\t exclude packages passed"
+    echo -e "\t-d, --delete\t delete existing links"
+    echo -e "\nArguments"
+    echo -e "\t<package>\t\t package basename to stow"
+    ;;
+  dump)
+    echo -e "Description"
+    echo -e "\t Dumps unlinked configs:"
+    echo -e "\t\t-Brewfile  (list of brew packages)"
+    echo -e "\t\t-Crontab   (cronjob settings)"
+    echo -e "\nUsage"
+    echo -e "\t$(basename "$2") dump [options]"
+    echo -e "\nOptions"
+    echo -e "\t-h, --help\t this helpful message"
+    ;;
+  *)
+    echo "Unknown help message '$1'"
+    exit 1
+    ;;
   esac
   exit 0
 }
@@ -70,14 +70,14 @@ function cmd_help() {
 
 # Check for Gnu Stow in path
 function stow_check() {
-  if ! ( which stow >/dev/null ); then
+  if ! (which stow >/dev/null); then
     echo -n "Gnu Stow not found in path, install it? (may require sudo) [Y/n]: "
     read -r IN
     IN=$(echo "$IN" | awk -F " " '{print tolower($0)}')
     if [ "$IN" == "y" ]; then
       # try install with brew
-      if ( which brew >/dev/null ); then
-        if _=$( brew install stow 2>&1 ); then
+      if (which brew >/dev/null); then
+        if _=$(brew install stow 2>&1); then
           echo "Installed with 'brew install stow'"
           echo
           return
@@ -86,17 +86,17 @@ function stow_check() {
         fi
       fi
       # gain sudo
-      if ! _=$( sudo -n true 2>&1 ); then
+      if ! _=$(sudo -n true 2>&1); then
         echo -n "Need sudo. "
-        if ! ( sudo echo -n "" ); then
+        if ! (sudo echo -n ""); then
           echo ""
           echo "Sudo failed, Exiting..."
           exit 1
         fi
       fi
       # try installing with apt
-      if ( which apt >/dev/null ); then
-        if _=$( sudo apt install -y stow 2>&1 ); then
+      if (which apt >/dev/null); then
+        if _=$(sudo apt install -y stow 2>&1); then
           echo "Installed with 'sudo apt install stow'"
           echo
           sudo -k
@@ -123,7 +123,7 @@ function cmd_stow() {
   STOWIGNORE="$DOT_DIR/.stowignore"
 
   # package regex
-  PACKAGE_REGEX=$DOT_DIR/*.$PACKAGE_EXTENSION
+  PACKAGE_REGEX=("$DOT_DIR"/*."$PACKAGE_EXTENSION")
 
   # default args
   STOW_ARGUMENTS=(
@@ -134,7 +134,7 @@ function cmd_stow() {
   )
 
   # help message
-  if [[ "$1" == "-h" || "$1" == "--help" ]] || (( $# == 0 )); then
+  if [[ $1 == "-h" || $1 == "--help" ]] || (($# == 0)); then
     cmd_help stow "$0"
   fi
 
@@ -149,27 +149,28 @@ function cmd_stow() {
   # parse arguments
   for ARG in "$@"; do
     case "$ARG" in
-      -a|--all)
-        ALL_FLAG=true
-        ;;
-      -t|--test)
-        STOW_ARGUMENTS+=("--no")
-        ;;
-      -e|--exclude)
-        EXCLUDE_FLAG=true
-        ;;
-      -d|--delete)
-        STOW_ARGUMENTS+=("--delete")
-        ;;
-      -h|--help)
-        cmd_help stow "$0"
-        ;;
-      *)
-        if ! [ -d "$DOT_DIR/$ARG.$PACKAGE_EXTENSION" ]; then
-          echo -e "Package Not Found: $ARG.$PACKAGE_EXTENSION"
-          exit 1
-        fi
-        TARGETS+=("$ARG.$PACKAGE_EXTENSION")
+    -a | --all)
+      ALL_FLAG=true
+      ;;
+    -t | --test)
+      STOW_ARGUMENTS+=("--no")
+      ;;
+    -e | --exclude)
+      EXCLUDE_FLAG=true
+      ;;
+    -d | --delete)
+      STOW_ARGUMENTS+=("--delete")
+      ;;
+    -h | --help)
+      cmd_help stow "$0"
+      ;;
+    *)
+      if ! [ -d "$DOT_DIR/$ARG.$PACKAGE_EXTENSION" ]; then
+        echo -e "Package Not Found: $ARG.$PACKAGE_EXTENSION"
+        exit 1
+      fi
+      TARGETS+=("$ARG.$PACKAGE_EXTENSION")
+      ;;
     esac
   done
 
@@ -180,31 +181,31 @@ function cmd_stow() {
   fi
   while IFS= read -r LINE; do
     # Skip empty lines and lines starting with #
-    [[ -z "$LINE" || "$LINE" =~ ^[[:space:]]*# ]] && continue
+    [[ -z $LINE || $LINE =~ ^[[:space:]]*# ]] && continue
     STOW_ARGUMENTS+=("--ignore=$LINE")
-  done < "$STOWIGNORE"
+  done <"$STOWIGNORE"
 
   if $ALL_FLAG; then
-    for pkg in $PACKAGE_REGEX; do
+    for pkg in "${PACKAGE_REGEX[@]}"; do
       pkg=$(basename "$pkg")
       STOW_ARGUMENTS+=("$pkg")
     done
   elif $EXCLUDE_FLAG; then
-    for pkg in $PACKAGE_REGEX; do
-        pkg=$(basename "$pkg")
-        skip=false
-        for target in "${TARGETS[@]}"; do
-          if [[ "$pkg" == "$target" ]]; then
-            skip=true
-            break
-          fi
-        done
-        if ! $skip; then
-          STOW_ARGUMENTS+=("$pkg")
+    for pkg in "${PACKAGE_REGEX[@]}"; do
+      pkg=$(basename "$pkg")
+      skip=false
+      for target in "${TARGETS[@]}"; do
+        if [[ $pkg == "$target" ]]; then
+          skip=true
+          break
         fi
       done
+      if ! $skip; then
+        STOW_ARGUMENTS+=("$pkg")
+      fi
+    done
   else
-    for TARGET in "${TARGETS[@]}" ; do
+    for TARGET in "${TARGETS[@]}"; do
       STOW_ARGUMENTS+=("$TARGET")
     done
   fi
@@ -220,8 +221,8 @@ function cmd_dump() {
   BREW_PATH="${STORAGE_DIR}/Brewfile"
   CRON_PATH="${STORAGE_DIR}/Cronjobs"
 
-  if (( $# != 0 )); then
-    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+  if (($# != 0)); then
+    if [[ $1 == "-h" || $1 == "--help" ]]; then
       cmd_help dump "$0"
     else
       echo "Dump takes no arguments"
@@ -251,24 +252,24 @@ function cmd_dump() {
 
 # ==================== SUBCOMMAND PARSER ====================
 
-if (( $# == 0 )); then
+if (($# == 0)); then
   cmd_help dot "$0"
 fi
 
 case "$1" in
-  -h|--help)
-    cmd_help dot "$0"
-    ;;
-  stow)
-    shift
-    cmd_stow "$@"
-    ;;
-  dump)
-    shift
-    cmd_dump "$@"
-    ;;
-  *)
-    echo "Unkown subcommand '$1'"
-    exit 1
-    ;;
+-h | --help)
+  cmd_help dot "$0"
+  ;;
+stow)
+  shift
+  cmd_stow "$@"
+  ;;
+dump)
+  shift
+  cmd_dump "$@"
+  ;;
+*)
+  echo "Unkown subcommand '$1'"
+  exit 1
+  ;;
 esac
